---
version: v1.2.20
dns: kan.{{ domain }}
exposed_port: 80
zfs:
  app: kanboard/app
  plugins: kanboard/plugins
healthcheck_url: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38333034646437363731306439633762323333633562316462383531393561663037643738373563
  3236646263303462343634383061653933323032373265330a383865393737323963636638373466
  37616133323434633361633639646631376632346433363238376230613930666264656464653135
  3362633464663163660a343134396435643030336562343533323736363065646239346165363466
  38623636653335323664643736353235363830643233356464336166613638363966356464643363
  63383666643233343563646137633966626630626436666639653830386634376461353934356336
  623037313031343464616166393833613161
