---
version: '1.0.1'
telegram_bot_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35656335646639616636656335646138326463343332326531336336353136393330663136623166
  3566333439633836633338386630306364363731653933630a356636663931656437663761353639
  63393164316133616539633066336531346339653233386337663032353434626438326438663137
  3030653133613365330a376233306133636538303539633634363430316665356632353564306336
  30383963626331663833646431646437313932343562373032363063313662643765333861316262
  3533376263643332306239363736313432666432623566633739
