---
dns: rpgbasement.xyz
exposed_port: 2368
zfs:
  blog: rpgbasement/blog
  podcast: rpgbasement/podcast
healthcheck_url: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37383034313639616631306663626531303832313531313031343563353439633533303132323165
  3464633863326163643036666166313434323639313738660a323631663639653162323564396233
  64303264643031656332313131623766363962666439666631653365386662333663366666633662
  6434616138633764320a363637346264383236303961393466636630393662626230393963306264
  66353961633236383065663838313136636536613265376564366361353036663866653536313865
  36663962326263656133323030633234306638306566613134633435363364383164626632653163
  306161623461386330343133343537323466
mailgun_user: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37643133363339356632356332666631646362333037303865346662653336336136626630336138
  3263373561313662343732343134393062303038653161650a323130363235633534616235376134
  35653631313131373835623834613832366537366334383364613830613732666666356539633537
  3261333434613234380a353365313236303932613738633931353738373533646261383533343738
  33333835656266663762376364666432356134303231356137326134393639666130

mailgun_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  33323737313231333333373266303961666432363932316562623963346330373164643235626662
  6337613166386437356438346236383532376238366161390a646639636661386366376532376138
  34323864363938613062633661353862313536613264646662613630636136396561303462646165
  3836393534633533350a616365623839356337333461656664613031373239643334373965636330
  33366636636630666361613630373463646663373430323934303739303732353263396135356331
  63643665666138633565376136363465396363636361303464653230343562333239343436316635
  396464366466646334303862613265326534
