---
appConfig:
  statusCheck: true
  hideComponents:
    hideSettings: true
  theme: 'nord'
  fontAwesomeKey: '0821c65656'
  layout: 'auto'
  iconSize: 'large'
pageInfo:
  title: 'Testchamber'
  navLinks:
    - title: 'Home'
      path: '/'
    - title: 'About'
      path: '/about'
    - title: 'Dashy'
      path: 'https://github.com/Lissy93/dashy'
  description: 'No cake this time'
  footerText: 'No cake this time'
sections:
  - name: 'HARDWARE'
    items:
      - title: 'EQ Router'
        description: 'keenetic viva'
        icon: 'https://icons.iconarchive.com/icons/icons8/ios7/512/Network-Router-icon.png'
        url: 'http://eq-router.lan.testchamber.one/'
      - title: 'Canterlot'
        description: 'Proxmox'
        icon: 'https://camo.githubusercontent.com/2df2ac41e1b8a1484be236c75e395981b31bfd670eff46b5c182ea0be9475310/68747470733a2f2f7777772e70726f786d6f782e636f6d2f696d616765732f70726f786d6f782f50726f786d6f785f73796d626f6c5f7374616e646172645f6865782e706e67'
        url: 'https://pve1.lan.testchamber.one/'
      - title: 'NA Router'
        description: 'tplink archer C7'
        icon: 'https://icons.iconarchive.com/icons/icons8/ios7/512/Network-Router-icon.png'
        url: 'http://na-router.lan.testchamber.one/'
  - name: 'INFRA'
    items:
      - title: 'Grafana'
        icon: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/Grafana_logo.svg/1920px-Grafana_logo.svg.png'
        url: 'https://mon.lan.testchamber.one/'
      - title: 'Prometheus'
        icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/1920px-Prometheus_software_logo.svg.png'
        url: 'https://prom.lan.testchamber.one/'
      - title: 'Alertmanager'
        icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/1920px-Prometheus_software_logo.svg.png'
        url: 'https://alerts.lan.testchamber.one/'
      - title: 'Portainer'
        icon: 'https://avatars.githubusercontent.com/u/22225832?s=200&v=4'
        url: 'https://swarm.lan.testchamber.one/'
      - title: 'Registry'
        icon: 'https://symbols.getvecta.com/stencil_27/31_container-registry.9b180a2bbf.png'
        url: 'https://registry.lan.testchamber.one/'
      - title: 'DNS'
        icon: 'https://developer.asustor.com/uploadIcons/0020_999_1595573028_AdGuardhome_256.png'
        url: 'http://adguard.lan.testchamber.one'
      - title: 'Healthchecks'
        description: 'Gatus'
        icon: 'https://status.vps1.phunsoft.de/img/logo.png'
        url: 'https://ping.lan.testchamber.one/'
      - title: 'Jenkins'
        icon: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Jenkins_logo.svg'
        url: 'https://ci.lan.testchamber.one/login'
      - title: 'Traefik'
        icon: 'https://traefik.io/static/traefik-proxy-logo--white-82153be41e0ce620a921b4bce974f6d8.svg'
        url: 'https://t.lan.testchamber.one/'
      - title: 'Authelia'
        icon: 'https://opencollective-production.s3.us-west-1.amazonaws.com/bf936590-3aae-11ea-a944-d5e45fdc60ab.png'
        url: 'https://auth.lan.testchamber.one/'
      - title: 'Speedtest'
        icon: 'https://img.icons8.com/material/452/ookla-speedtest.png'
        url: 'https://speed.lan.testchamber.one/'
        # statusCheck: false
  - name: 'SYNC'
    items:
      - title: 'EQ'
        icon: 'https://upload.wikimedia.org/wikipedia/commons/8/83/SyncthingAugustLogo.png'
        url: 'https://sync.lan.testchamber.one/'
      - title: 'NA'
        icon: 'https://upload.wikimedia.org/wikipedia/commons/8/83/SyncthingAugustLogo.png'
        url: 'http://manehattan.lan.testchamber.one:8384/'
  - name: 'INTERNAL'
    items:
      - title: 'Paperless'
        icon: 'https://user-images.githubusercontent.com/63257521/115958086-d01a5580-a4fd-11eb-9273-6f2bd749bcef.png'
        url: 'https://paper.lan.testchamber.one'
      - title: 'qBittorrent'
        icon: 'https://upload.wikimedia.org/wikipedia/commons/6/66/New_qBittorrent_Logo.svg'
        url: 'https://p2p.lan.testchamber.one/'
      - title: 'Jellyfin'
        icon: 'https://developer.asustor.com/uploadIcons/0020_999_1568614440_Jellyfin_256.png'
        url: 'http://theatre.lan.testchamber.one/'
      - title: 'Youtube-dl'
        icon: 'https://icons.iconarchive.com/icons/papirus-team/papirus-apps/512/youtube-dl-icon.png'
        url: 'https://ss.lan.testchamber.one/'
      - title: 'Grocy'
        icon: 'https://cdn-icons-png.flaticon.com/512/1261/1261163.png'
        url: 'https://erp.lan.testchamber.one/'
  - name: 'EXTERNAL'
    items:
      - title: 'TTRSS'
        icon: 'https://git.tt-rss.org/repo-avatars/3-9e1f83d2fac71ea097eeaf1776137cde'
        url: 'https://rss.testchamber.one/'
      - title: 'Etherpad'
        icon: 'https://pbs.twimg.com/profile_images/1336377123964145665/2gTadaDt_400x400.jpg'
        url: 'https://pad.testchamber.one/'
      - title: 'Kanboard'
        icon: 'https://yunohost.org/user/images/kanboard_logo.png'
        url: 'https://kan.testchamber.one/'
      - title: 'Nextcloud'
        icon: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Nextcloud_Logo.svg'
        url: 'https://cloud.testchamber.one/'
  - name: 'TTRPG'
    items:
      - title: 'RPG Basement'
        icon: favicon
        url: 'https://rpgbasement.xyz'
      - title: 'Podcast hosting'
        icon: 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Podcasts_%28iOS%29.svg'
        url: 'https://host.rpgbasement.xyz/podcast'