---
domain: testchamber.one
lan: 'lan.{{ domain }}'

public_ip: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31306164656137376363653965393064656232646233623931343439623430313736336566373737
  3362316263666563623738383335363661343832643836310a613661653531653332373934343662
  62623038333766343539393931346233616365323431326432643164353236393638323831316438
  3762323464333132630a393437653063306431383362633265303234653237626261633133633331
  3231

ignored_users:
  - nobody # default linux user
  - ceph # proxmox
  - wunder # me
  - ci # ci

ansible_become_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63323232633963613637383237373235636230326438386263383831383034356336333266613332
  3364333735623935653361653565316234396239343231360a303733313438303232313735663135
  34313334626337643363663134353132393966346133653665303633626231343237346439366334
  3837336531396163610a396633643665353463376433386365313537336537323038396633643630
  62633766653662323965326238323034343035366466613466663936376230326238

do_auth_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65666162613931383537646531313463353366333165613835393335616336363739376161393864
  6563313437636631666265366433616130643835353330650a353061316334306530643263336131
  66393162303934333634303937396564623437386135383033613761656432323564623266323638
  6132323337336666310a656135313264303565383638663939616232343531643132363430626563
  36666334636362663934653731613066353838333333363237633337323735623364363135353633
  64343262353862356339663232313163346666663034633762366538303436366537333033343334
  65316437333761353533616335386362353236386337653530353539303134363562643164386137
  66633538613861376463

registry:
  url: reg.{{ lan }}
  pass: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    32623664623436326131643134643431333465353236326430326230663630323634333830346131
    6162643633316161386130616230303365643735633332630a336166366539376435616665303939
    62336533386366353263313836633238376265303062636337366236356330316365393639323163
    6530653137656130610a373734393138386334376563656161663439613766636565353633396265
    3163
